// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZlF_M-KjntXHlAfHyjIaiDO4gU8jWYPg',
    appId: '1:462653983121:web:0f0d86e34690afca4c7230',
    messagingSenderId: '462653983121',
    projectId: 'aspire-cb886',
    authDomain: 'aspire-cb886.firebaseapp.com',
    storageBucket: 'aspire-cb886.firebasestorage.app',
    measurementId: 'G-J8691FZ3ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVswG1Wc3FEDLLoG3y3Tu6wSN__pHX43g',
    appId: '1:462653983121:android:0ba62a1887ee92844c7230',
    messagingSenderId: '462653983121',
    projectId: 'aspire-cb886',
    storageBucket: 'aspire-cb886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbt-6hn_HMGhU3Cm9VVx8ytG73kZ4MTM',
    appId: '1:462653983121:ios:0e981b5a3ec42d824c7230',
    messagingSenderId: '462653983121',
    projectId: 'aspire-cb886',
    storageBucket: 'aspire-cb886.firebasestorage.app',
    iosBundleId: 'com.example.aspireTaskProFrontend',
  );
}
